

spring:
  application:
    name: ORDER-SERVICE


# Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: system


  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


# Server port
server:
  port: 8082
