

spring:
  application:
    name: ORDER-SERVICE


# Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/order_service
    username: root
    password: system


  # Hibernate properties
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server




management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always



# Resilience4j Properties.

resilience4j:
  circuitbreaker:
    instances:
      inventory:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s




# Server port
server:
  port: 8082
