

spring:
  application:
    name: PRODUCT-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service


  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server


server:
  port: 8081