spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_service
    username: root
    password: system

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  cloud:
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server



server:
  port: 8083